### ISSUE TITLE
How can it integrate with other library?

### ISSUE THREAD

**Issue by zjkmxy** [named-data/StateVectorSync#1]
For example, when I call `publishData`, how to specify the way that the data is signed/encrypted?
Do I have to use `Logic` instead of `Socket` for security integration?

**Comment by phylib** [comment]
Hi @zjkmxy,
thanks for taking a look. We define our API in the file `API.md`. The constructor of Socket and Logic both take Security options. If you take a look to [SecurityOptions](https://github.com/named-data/ndn-svs/blob/29502759bb9869d7fac917e9ed27e14eaefb07cb/ndn-svs/security-options.hpp#L38) in the C++ implementation, you can see that it allows defining the signer identity for both, the SyncInterest, and the publication Data.

In your opinion, is it sufficient to provide the signer identity? Or do we need more than that?

In general when using StateVectorSync, applications should use the `Socket`. This provides an abstraction for all the protocol details.

**Comment by Pesa** [comment]
@phylib ndn-cxx already defines a (fairly) general interface that abstracts and encapsulates the parameters necessary for packet signing: the [SigningInfo](https://github.com/named-data/ndn-cxx/blob/5dc7560d5dbcdf2588796f315f15c9704a2a314f/ndn-cxx/security/signing-info.hpp#L52) class.

Other than maybe the poor documentation ( 😛 ) what prevented you from using it in the ndn-svs API? If you have any suggestions to make SigningInfo suitable for ndn-svs, I think the ndn-cxx devs would be happy to hear them, so that we can avoid reinventing the wheel in ndn-svs.

**Comment by phylib** [comment]
@Pesa, thanks for the pointer. I guess the reason we did not use it was that we were not aware of that class :see_no_evil:

We'll discuss in our small group of developers and check if we can use it. But from a first look to the class, it seems to be well suited!

**Comment by pulsejet** [comment]
@Pesa good point, that class can be reused here. One difference is that `SecurityOptions` also contains the validator and data security options, so I'll just change the struct to include two instances of `SigningInfo` (one for sync interests, the other for data).

**Comment by pulsejet** [comment]
Updated, please take look.
