### ISSUE TITLE
Pub/Sub protocol spec

### ISSUE THREAD

**Issue by pulsejet** [named-data/StateVectorSync#4]
The spec for the Pub/Sub needs to be documented.

Reported by @yoursunny

**Comment by pulsejet** [comment]
https://github.com/named-data/StateVectorSync/commit/00b9fd817d5468977fa54020d803bb1ab55e57e2

**Comment by yoursunny** [comment]
The update only includes the **API** of pubsub, which is mostly useless because it duplicates Doxygen.

What I asked for is the **protocol specification** of pubsub:

* How things are encoded.
* How does each entity react to each event.

A successful protocol specification must allow an interoperable implementation to be created without consulting the source code of any reference implementation.
